security:

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            logout:
                path: app_logout
                target: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                path: /

    access_control:
        - { path: '^/(_(profiler|wdt)|css|images|js)/', roles: PUBLIC_ACCESS }
        - { path: '^/[a-z]{2}/login', roles: PUBLIC_ACCESS }
        - { path: '^/[a-z]{2}/register', roles: PUBLIC_ACCESS }
        - { path: '^/[a-z]{2}/$', roles: PUBLIC_ACCESS }

        - { path: '^/[a-z]{2}/profile', roles: ROLE_USER }
        - { path: '^/[a-z]{2}/coach', roles: ROLE_COACH }
        - { path: '^/[a-z]{2}/client', roles: ROLE_CLIENT }